# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  #servlet:
    #context-path: /bpm

spring:
  #Activiti property configuration
  activiti:
    #首次启动项目打开注释，标自动床架能成功后关闭注释
    #database-schema: ACT
    database-schema-update: true
    job-executor-activate: true
    check-process-definitions: false
    
  datasource:
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521/orcl
      username: activity
      password: activity
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒 
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小 
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
    properties:
      hibernate: 
        dialect:org.hibernate.dialect.Oracle11gDialect

#平台配置
we:
 config:
   login-page-app-name: bpm集成开发平台
   use-conc: false
 httpclient:
   #最大连接数
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 100000000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
 
  